### ISSUE TITLE
Base II not switching to drum machine mode anymore since Bitwig 2.2 update

### ISSUE THREAD

**Issue by rdamen** [LividInstruments/Bitwig#4]
Hi,

Since Bitwig update 2.2 (I think) it's not switching the layout of my Base II to drum machine anymore when I select a drum machine track.
I don't have much time to look into it myself but with a quick glance at the code I think something is probably going wrong this line (or related to it):
https://github.com/LividInstruments/Bitwig/blob/master/BASEII.control.js#L717

I hope you can fix it!

Thanks,
Ron

**Comment by aumhaa** [comment]
I’ll try to check it out in the next day or so….this has been an ongoing problem with Bitwig since I wrote these scripts, the problem is with the API not reporting the correct values to the script.  It’s been reported to them.  I’ll see if the situation has changed….my previous experience was that “sometimes it works, sometimes it doesn’t….”

a

**Comment by rdamen** [comment]
My bad, after updating to the latest version (correctly this time) it's working as intended.
I unpacked the zip into a new subdirectory before by mistake.
Sorry for bothering you. Thanks for your work it's a joy to use.

**Comment by aumhaa** [comment]
No worries, thanks for getting back :)

a
